<?php
// This file generated by Propel 1.5.2 convert-conf target
// from XML runtime conf file C:\dev\runtime-conf.xml
$conf = array(
    'datasources' =>
    array(
        'mathgraph' =>
        array(
            'adapter' => 'mysql',
            'connection' =>
            array(
                'dsn' => 'mysql:host=localhost;dbname=mathgraph',
                'user' => 'root',
                'password' => '',
            ),
        ),
    ),
    'generator_version' => '1.5.2',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-mathgraph-conf.php');
return $conf;